from pathlib import Path
import math, csv, json, runpy
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
ns=runpy.run_path('/mnt/data/pchem_build/generate_site.py')
R,NA,KB=ns['R'],ns['NA'],ns['KB']
ROOT=Path('/mnt/data/physical_chemistry_course'); FIGS=ROOT/'assets/figures'; DATA=ROOT/'assets/data'
FIGS.mkdir(parents=True,exist_ok=True); DATA.mkdir(parents=True,exist_ok=True)
plt.rcParams.update({'figure.dpi':130,'savefig.bbox':'tight','font.size':10})
V={}
def csvsave(name,heads,rows):
    with (DATA/f'{name}.csv').open('w',newline='',encoding='utf-8') as f:
        w=csv.writer(f);w.writerow(heads);w.writerows(rows)
    return name+'.csv'
def plot(name,title,xlabel,ylabel,series,xlim=None,ylim=None,yscale=None,points=None):
    fig,ax=plt.subplots(figsize=(7.1,4.4))
    for x,y,label in series: ax.plot(x,y,label=label)
    if points:
        for x,y,label in points: ax.scatter(x,y,label=label,zorder=5)
    if any(s[2] for s in series) or points: ax.legend(fontsize=8)
    ax.set_title(title);ax.set_xlabel(xlabel);ax.set_ylabel(ylabel);ax.grid(True,alpha=.25)
    if xlim: ax.set_xlim(*xlim)
    if ylim: ax.set_ylim(*ylim)
    if yscale: ax.set_yscale(yscale)
    fig.savefig(FIGS/f'{name}.svg');plt.close(fig)
def svg(name,body,w=820,h=440):
    txt=f'''<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}"><style>text{{font-family:Arial,sans-serif;fill:#14213d}}.s{{stroke:#14213d;stroke-width:3;fill:none}}.f{{fill:#f7f1e3;stroke:#b58b2a;stroke-width:2}}.g{{stroke:#b58b2a;stroke-width:3;fill:none}}.d{{stroke:#5b6472;stroke-width:2;stroke-dasharray:8 7;fill:none}}</style>{body}</svg>'''
    (FIGS/f'{name}.svg').write_text(txt,encoding='utf-8')
def meta(n,file,data,type,en,ar,ae,aa,ie,ia):V[n]=dict(file=file,data=data,type=type,title_en=en,title_ar=ar,alt_en=ae,alt_ar=aa,interp_en=ie,interp_ar=ia)
# 1 van der Waals
x=np.linspace(.36,4,500);series=[];rows=[]
for T in [.85,1,1.25]:
 y=8*T/(3*x-1)-3/x**2;m=(y>-1)&(y<5);series.append((x[m],y[m],f'Tᵣ={T:g}'));rows += [[T,float(a),float(b)] for a,b in zip(x[::10],y[::10])]
plot('fig01_vdw_isotherms','Reduced van der Waals isotherms','Reduced molar volume Vᵣ','Reduced pressure pᵣ',series,(.35,4),(-.5,4.3),points=[([1],[1],'critical point')]);d=csvsave('fig01_vdw_isotherms',['Tr','Vr','Pr'],rows)
meta(1,'fig01_vdw_isotherms.svg',d,'theoretical graph','Reduced van der Waals isotherms and the critical point','متساويات حرارة فان دير فالس المختزلة والنقطة الحرجة','Reduced pressure versus reduced molar volume at three temperatures with critical point at one, one.','الضغط المختزل مقابل الحجم المختزل عند ثلاث درجات حرارة مع النقطة الحرجة عند واحد وواحد.','Below the critical temperature the model develops a non-monotonic loop; at Tᵣ=1 the critical inflection lies at pᵣ=Vᵣ=1. The loop is a warning that homogeneous van der Waals theory does not itself describe the stable two-phase region.','تحت الحرارة الحرجة تظهر حلقة غير رتيبة؛ وعند Tᵣ=1 تقع نقطة الانعطاف الحرجة عند pᵣ=Vᵣ=1. وتنبه الحلقة إلى أن نموذج فان دير فالس المتجانس لا يصف وحده منطقة الطورين المستقرة.')
# 2 Maxwell
v=np.linspace(0,1500,500);m=.0280134/NA;series=[];rows=[]
for T in [200,300,600]:
 y=4*np.pi*(m/(2*np.pi*KB*T))**1.5*v**2*np.exp(-m*v*v/(2*KB*T));series.append((v,y,f'{T} K'));rows += [[T,float(a),float(b)] for a,b in zip(v[::10],y[::10])]
plot('fig02_maxwell','Maxwell speed distributions for N₂','Speed / m s⁻¹','Probability density / s m⁻¹',series);d=csvsave('fig02_maxwell',['T_K','speed_m_s','density'],rows)
meta(2,'fig02_maxwell.svg',d,'calculated theoretical graph','Maxwell speed distribution and temperature','توزيع ماكسويل للسرعات وتأثير الحرارة','Three nitrogen speed distributions at 200, 300, and 600 kelvin; peaks shift right and broaden with temperature.','ثلاثة توزيعات سرعات للنيتروجين عند 200 و300 و600 كلفن؛ تتحرك القمم يميناً وتتسع مع الحرارة.','Heating broadens the unit-area distribution and shifts molecular population toward higher speeds. Most-probable, mean, and rms speeds are distinct summaries of this same distribution.','يرفع التسخين نسبة الجزيئات السريعة ويوسع التوزيع مع ثبات مساحته الكلية. السرعة الأكثر احتمالاً والمتوسطة والجذرية المتوسطة مقاييس مختلفة للتوزيع نفسه.')
# 3 pV paths
x=np.linspace(1,4,250);y1=4/x;y2=4/x**1.4
plot('fig03_pv_work','Expansion paths on a p–V diagram','Relative volume','Relative pressure',[(x,y1,'isothermal'),(x,y2,'adiabatic')]);d=csvsave('fig03_pv_work',['Vrel','p_isothermal','p_adiabatic'],zip(x[::5],y1[::5],y2[::5]))
meta(3,'fig03_pv_work.svg',d,'idealized theoretical graph','Pressure–volume paths and boundary work','مسارات الضغط–الحجم وشغل الحدود','Pressure-volume curves comparing isothermal and adiabatic expansion.','منحنيات ضغط–حجم تقارن التمدد المتساوي الحرارة بالتمدد الأديباتي.','Boundary work is path-dependent because it integrates pressure over volume change. Different constraints produce different pressure histories and therefore different work for the same volume change.','شغل الحدود يعتمد على المسار لأنه يكامل الضغط مع تغير الحجم؛ فالقيود المختلفة تعطي تواريخ ضغط وشغلاً مختلفين لنفس تغير الحجم.')
# 4 Carnot T-S
x=np.array([1,4,4,1,1]);y=np.array([600,600,300,300,600]);plot('fig04_carnot_ts','Reversible Carnot cycle on T–S plane','Entropy S (arbitrary units)','Temperature / K',[(x,y,'cycle')])
meta(4,'fig04_carnot_ts.svg',None,'conceptual thermodynamic diagram','Carnot cycle and entropy transfer','دورة كارنو وانتقال الإنتروبيا','Rectangular Carnot cycle on temperature-entropy coordinates between 600 and 300 kelvin.','دورة كارنو مستطيلة على إحداثيات الحرارة–الإنتروبيا بين 600 و300 كلفن.','For reversible heat, δq_rev=T dS; the area enclosed on a T–S diagram is the net cycle work. This makes the second-law efficiency limit geometrically visible.','للحرارة العكوسة δq_rev=T dS؛ وتمثل المساحة المحصورة على مخطط T–S الشغل الصافي للدورة، فتظهر حدود كفاءة القانون الثاني هندسياً.')
# 5 phase diagram schematic
svg('fig05_phase_diagram','''<path class="s" d="M90 370 C180 330 250 270 330 210"/><path class="s" d="M330 210 C440 150 600 115 730 95"/><path class="s" d="M330 210 C300 150 285 95 280 45"/><circle class="f" cx="330" cy="210" r="7"/><circle class="f" cx="730" cy="95" r="7"/><text x="130" y="110" font-size="23">solid</text><text x="405" y="95" font-size="23">liquid</text><text x="530" y="330" font-size="23">vapour</text><text x="342" y="225" font-size="17">triple point</text><text x="600" y="75" font-size="17">critical point</text><text x="360" y="420" font-size="20">Temperature →</text><text x="20" y="80" font-size="20">Pressure ↑</text>''')
meta(5,'fig05_phase_diagram.svg',None,'conceptual phase diagram','One-component phase equilibria','اتزانات الأطوار لمكوّن واحد','Schematic pressure-temperature phase diagram showing solid, liquid, vapour, triple point, and critical point.','مخطط ضغط–حرارة تخطيطي يوضح الصلب والسائل والبخار والنقطة الثلاثية والحرجة.','Coexistence curves contain states where two phases have equal chemical potential. All three meet at the triple point; the liquid–vapour line terminates at the critical point. The precise scale is substance-specific.','تحتوي منحنيات التعايش على الحالات التي يتساوى فيها الكمون الكيميائي لطورين. تلتقي الثلاثة عند النقطة الثلاثية وينتهي خط السائل–البخار عند النقطة الحرجة. المقياس الدقيق خاص بالمادة.')
# 6 ideal VLE
x=np.linspace(0,1,201);P=40+60*x;y=100*x/P
plot('fig06_raoult','Ideal binary VLE at fixed T','Liquid or vapour mole fraction A','Pressure / kPa',[(x,P,'bubble vs xA'),(y,P,'dew vs yA')]);d=csvsave('fig06_raoult',['xA','P_kPa','yA'],zip(x[::4],P[::4],y[::4]))
meta(6,'fig06_raoult.svg',d,'calculated ideal-solution graph','Raoult-law bubble and dew curves','منحنيات الفقاع والندى لقانون راؤولت','Pressure-composition diagram for an ideal binary mixture with pure vapour pressures 100 and 40 kilopascals.','مخطط ضغط–تركيب لمزيج ثنائي مثالي بضغطَي بخار نقيين 100 و40 كيلوباسكال.','The vapour is richer in the more volatile component A, so yA exceeds xA through most of the two-phase region. This separation is the basis of distillation.','يكون البخار أغنى بالمكوّن الأكثر تطايراً A، لذا تتجاوز yA قيمة xA في معظم منطقة الطورين، وهو أساس التقطير.')
# 7 Debye-Huckel
I=np.linspace(.0001,.1,240);s=np.sqrt(I);series=[];rows=[]
for z in [1,2]:
 y=-.509*z*z*s;series.append((s,y,f'|z|={z}'));rows += [[z,float(a),float(b)] for a,b in zip(s[::5],y[::5])]
plot('fig07_debye_huckel','Debye–Hückel limiting law','√I / (mol L⁻¹)¹ᐟ²','log₁₀ γᵢ',series);d=csvsave('fig07_debye_huckel',['abs_z','sqrtI','log10gamma'],rows)
meta(7,'fig07_debye_huckel.svg',d,'calculated limiting-law graph','Activity coefficients at low ionic strength','معاملات النشاط عند القوة الأيونية المنخفضة','Log activity coefficient decreases linearly with square root ionic strength; divalent ions have a steeper line.','ينخفض لوغاريتم معامل النشاط خطياً مع جذر القوة الأيونية ويكون خط الأيون الثنائي أشد ميلاً.','The limiting law predicts log γ proportional to −z²√I only at low ionic strength. Ion size, specific association, and short-range interactions limit extrapolation to concentrated solutions.','يتنبأ القانون الحدي بأن log γ يتناسب مع −z²√I فقط عند القوة الأيونية المنخفضة؛ تحد أحجام الأيونات والارتباط النوعي والتآثرات القصيرة استقراءه للمحاليل المركزة.')
# 8 reaction quotient
x=np.logspace(-2,2,250);y=np.log(x);plot('fig08_equilibrium_q','Reaction direction from ΔᵣG = RT ln(Q/K)','Q/K','ΔᵣG / RT',[(x,y,'ΔᵣG/RT')]);d=csvsave('fig08_equilibrium_q',['Q_over_K','dG_over_RT'],zip(x[::5],y[::5]))
meta(8,'fig08_equilibrium_q.svg',d,'theoretical graph','Reaction quotient, Gibbs energy, and equilibrium','حاصل التفاعل وطاقة غيبس والاتزان','Dimensionless reaction Gibbs energy crosses zero when Q equals K.','طاقة غيبس التفاعلية اللابعدية تعبر الصفر عندما يساوي Q قيمة K.','Q<K gives ΔᵣG<0 and forward spontaneous change; Q>K favors the reverse direction; Q=K is equilibrium.','عندما Q<K تكون ΔᵣG<0 ويُفضّل الاتجاه الأمامي؛ وعندما Q>K يُفضّل العكسي؛ وعند Q=K يتحقق الاتزان.')
# 9 galvanic cell
svg('fig09_cell','''<rect class="f" x="60" y="120" width="260" height="210" rx="18"/><rect class="f" x="500" y="120" width="260" height="210" rx="18"/><line class="s" x1="165" y1="80" x2="165" y2="275"/><line class="s" x1="655" y1="80" x2="655" y2="275"/><path class="s" d="M165 80 C280 30 540 30 655 80"/><rect class="f" x="365" y="22" width="90" height="55" rx="10"/><text x="397" y="58" font-size="23">V</text><path class="g" d="M320 190 C380 145 440 145 500 190"/><path class="g" d="M320 240 C380 285 440 285 500 240"/><text x="120" y="310" font-size="20">Zn²⁺</text><text x="620" y="310" font-size="20">Cu²⁺</text><text x="130" y="70" font-size="20">Zn</text><text x="625" y="70" font-size="20">Cu</text><text x="325" y="140" font-size="17">salt bridge</text><text x="305" y="105" font-size="17">electron flow →</text><text x="90" y="375" font-size="18">anode: oxidation</text><text x="555" y="375" font-size="18">cathode: reduction</text>''')
meta(9,'fig09_cell.svg',None,'original schematic','Galvanic cell: electron and ion pathways','خلية جلفانية: مسارا الإلكترونات والأيونات','Zinc-copper galvanic cell with two electrodes, salt bridge, external wire, voltmeter, and electron flow.','خلية جلفانية زنك–نحاس مع قطبين وجسر ملحي ودائرة خارجية وفولتميتر وتدفق الإلكترونات.','Oxidation releases electrons at the anode and reduction consumes them at the cathode. The salt bridge transports ions to maintain electroneutrality; electrons do not flow through the salt bridge.','تحرر الأكسدة الإلكترونات عند المصعد ويستهلكها الاختزال عند المهبط. ينقل الجسر الملحي الأيونات للمحافظة على التعادل الكهربائي ولا تمر فيه الإلكترونات.')
# 10 particle in box
x=np.linspace(0,1,500);series=[];rows=[]
for n in [1,2,3]:
 y=n*n+.55*np.sin(n*np.pi*x);series.append((x,y,f'n={n}'));rows += [[n,float(a),float(b)] for a,b in zip(x[::10],y[::10])]
plot('fig10_box','Particle in a one-dimensional box','Position x/L','Relative energy + offset ψₙ',series,ylim=(0,10));d=csvsave('fig10_box',['n','x_over_L','offset_wavefunction'],rows)
meta(10,'fig10_box.svg',d,'calculated quantum model','Quantized box energies and stationary waves','طاقات الصندوق المكمّاة والموجات الساكنة','First three sine wavefunctions displayed at energies proportional to n squared in an infinite one-dimensional box.','الدوال الموجية الجيبية الثلاث الأولى مع طاقات تتناسب مع مربع n في صندوق لا نهائي أحادي البعد.','Boundary conditions force ψ to vanish at the walls, selecting discrete wavelengths and energies proportional to n². Higher states contain more nodes; the plotted amplitude is vertically offset for visibility.','تفرض شروط الحدود انعدام ψ عند الجدران فتختار أطوالاً موجية وطاقات متقطعة تتناسب مع n². تحتوي الحالات الأعلى عقداً أكثر، ومطال الدالة مزاح رأسياً لسهولة الرؤية.')
# 11 spectroscopy ladders
svg('fig11_levels','''<text x="70" y="45" font-size="24">Rotational</text><text x="500" y="45" font-size="24">Vibrational</text><line class="s" x1="100" y1="350" x2="320" y2="350"/><line class="s" x1="100" y1="300" x2="320" y2="300"/><line class="s" x1="100" y1="215" x2="320" y2="215"/><line class="s" x1="100" y1="95" x2="320" y2="95"/><text x="55" y="356" font-size="18">J=0</text><text x="55" y="306" font-size="18">J=1</text><text x="55" y="221" font-size="18">J=2</text><text x="55" y="101" font-size="18">J=3</text><path class="g" d="M250 345 L250 307"/><text x="265" y="330" font-size="18">ΔJ=+1</text><line class="s" x1="500" y1="350" x2="730" y2="350"/><line class="s" x1="500" y1="250" x2="730" y2="250"/><line class="s" x1="500" y1="150" x2="730" y2="150"/><line class="s" x1="500" y1="50" x2="730" y2="50"/><text x="460" y="356" font-size="18">v=0</text><text x="460" y="256" font-size="18">v=1</text><text x="460" y="156" font-size="18">v=2</text><text x="460" y="56" font-size="18">v=3</text><path class="g" d="M660 345 L660 257"/><text x="680" y="306" font-size="18">Δv=+1</text>''')
meta(11,'fig11_levels.svg',None,'original energy-level schematic','Rotational and vibrational spectroscopic ladders','سلالم الطاقة الدورانية والاهتزازية الطيفية','Rotational levels with increasing spacing and harmonic vibrational levels with equal spacing, each with an upward transition arrow.','مستويات دورانية متزايدة التباعد ومستويات اهتزازية توافقية متساوية التباعد مع سهم انتقال صاعد.','Rigid-rotor spacings grow with J because E_J∝J(J+1), whereas harmonic-oscillator levels are equally spaced. Real spectra add anharmonicity, centrifugal distortion, and symmetry selection rules.','تزداد المسافات الدورانية مع J لأن E_J∝J(J+1)، بينما تتساوى مستويات المهتز التوافقي. تضيف الأطياف الحقيقية اللاّتوافق وتشوه الطرد المركزي وقيود التناظر.')
# 12 radial probability
r=np.linspace(0,15,500);p1=4*r*r*np.exp(-2*r);p2=r*r*(2-r)**2*np.exp(-r)/8;p1/=p1.max();p2/=p2.max()
plot('fig12_radial','Hydrogen radial probability distributions (scaled)','r / a₀','Relative radial probability',[(r,p1,'1s'),(r,p2,'2s')]);d=csvsave('fig12_radial',['r_over_a0','P1s','P2s'],zip(r[::10],p1[::10],p2[::10]))
meta(12,'fig12_radial.svg',d,'calculated quantum graph','Hydrogen radial probability and nodes','الاحتمال الشعاعي للهيدروجين والعقد','Scaled radial probability for hydrogen 1s and 2s, with a radial node in the 2s distribution.','احتمال شعاعي مقياس للهيدروجين 1s و2s مع عقدة شعاعية في توزيع 2s.','Radial probability contains |R|² and the spherical-shell factor 4πr². It describes probability at a radius, not the sign of the orbital. The 2s radial node is a spherical zero-probability surface.','يتضمن الاحتمال الشعاعي |R|² وعامل القشرة 4πr²، فيصف الاحتمال عند نصف قطر لا إشارة المدار. عقدة 2s سطح كروي لانعدام الاحتمال.')
# 13 MO
svg('fig13_mo','''<text x="80" y="35" font-size="22">AO(A)</text><text x="385" y="35" font-size="22">MOs</text><text x="680" y="35" font-size="22">AO(B)</text><line class="s" x1="75" y1="220" x2="220" y2="220"/><line class="s" x1="600" y1="220" x2="745" y2="220"/><line class="s" x1="330" y1="320" x2="500" y2="320"/><line class="s" x1="330" y1="120" x2="500" y2="120"/><path class="d" d="M220 220 L330 320 M220 220 L330 120 M600 220 L500 320 M600 220 L500 120"/><text x="390" y="350" font-size="18">σ bonding</text><text x="380" y="105" font-size="18">σ* antibonding</text><text x="390" y="307" font-size="28">↑↓</text><text x="350" y="410" font-size="18">bond order = 1</text><text x="25" y="70" font-size="18">Energy ↑</text>''')
meta(13,'fig13_mo.svg',None,'original molecular-orbital schematic','Bonding and antibonding molecular orbitals','المدارات الجزيئية الرابطة والمضادة للرابطة','Two atomic orbitals combine into lower bonding and higher antibonding molecular orbitals, with two electrons in the bonding level.','مداران ذريان يتحدان إلى مدار جزيئي رابط منخفض ومضاد للرابطة مرتفع مع إلكترونين في المستوى الرابط.','Two compatible atomic orbitals generate one stabilizing and one destabilizing molecular orbital. Electron occupancy determines bond order and magnetic behavior.','يولد مداران ذريان متوافقان مداراً رابطاً مثبتاً وآخر مضاداً للرابطة مزعزعاً، ويحدد إشغال الإلكترونات رتبة الرابطة والسلوك المغناطيسي.')
# 14 Jablonski
svg('fig14_jablonski','''<line class="s" x1="120" y1="360" x2="330" y2="360"/><line class="s" x1="120" y1="220" x2="330" y2="220"/><line class="s" x1="120" y1="95" x2="330" y2="95"/><line class="s" x1="520" y1="250" x2="730" y2="250"/><text x="80" y="367" font-size="20">S₀</text><text x="80" y="227" font-size="20">S₁</text><text x="80" y="102" font-size="20">S₂</text><text x="480" y="257" font-size="20">T₁</text><path class="g" d="M175 350 L175 105"/><text x="190" y="175" font-size="18">absorption</text><path class="d" d="M275 105 L275 210"/><text x="290" y="165" font-size="17">IC</text><path class="g" d="M210 230 L210 350"/><text x="225" y="300" font-size="18">fluorescence</text><path class="d" d="M330 225 C400 205 450 230 520 245"/><text x="385" y="205" font-size="17">ISC</text><path class="g" d="M620 260 L620 350"/><text x="635" y="315" font-size="18">phosphorescence</text>''')
meta(14,'fig14_jablonski.svg',None,'original photophysical schematic','Jablonski diagram for electronic relaxation','مخطط جابلونسكي للاسترخاء الإلكتروني','Electronic state diagram with absorption, internal conversion, fluorescence, intersystem crossing, and phosphorescence.','مخطط حالات إلكترونية مع الامتصاص والتحول الداخلي والفلورية والعبور بين الأنظمة والفسفورية.','Absorption is rapid; competing radiative and nonradiative pathways redistribute excited-state population. Relative rates determine fluorescence/phosphorescence lifetimes and quantum yields.','الامتصاص سريع، وتتنافس المسارات الإشعاعية وغير الإشعاعية على سكان الحالة المثارة. تحدد السرعات النسبية أزمنة الحياة والمردود الكمومي للفلورية والفسفورية.')
# 15 Arrhenius
T=np.linspace(270,500,220);x=1/T;y=np.log(1e10*np.exp(-50000/(R*T)))
plot('fig15_arrhenius','Arrhenius linearization (Eₐ = 50 kJ mol⁻¹)','1/T / K⁻¹','ln k',[(x,y,'model')]);d=csvsave('fig15_arrhenius',['T_K','inverseT','lnk'],zip(T[::5],x[::5],y[::5]))
meta(15,'fig15_arrhenius.svg',d,'calculated kinetic graph','Arrhenius plot and activation energy','مخطط أرينيوس وطاقة التنشيط','Straight line of ln k versus reciprocal temperature for a model with activation energy 50 kilojoules per mole.','خط مستقيم لـln k مقابل مقلوب الحرارة لنموذج بطاقة تنشيط 50 كيلوجول لكل مول.','For constant A and Eₐ, slope=−Eₐ/R. Curvature in experimental data can flag temperature-dependent parameters, tunnelling, or a change of mechanism.','عند ثبات A وEₐ يكون الميل −Eₐ/R. قد يشير الانحناء التجريبي إلى اعتماد المعلمات على الحرارة أو النفق أو تغير الآلية.')
# 16 ozone cycle
svg('fig16_ozone','''<circle class="f" cx="180" cy="220" r="80"/><circle class="f" cx="410" cy="105" r="80"/><circle class="f" cx="640" cy="220" r="80"/><text x="145" y="228" font-size="25">O₂</text><text x="400" y="113" font-size="25">O</text><text x="605" y="228" font-size="25">O₃</text><path class="g" d="M245 170 C300 115 325 95 330 95"/><text x="250" y="85" font-size="17">hν</text><path class="g" d="M475 125 C535 145 565 165 584 180"/><text x="500" y="125" font-size="17">+ O₂ + M</text><path class="g" d="M590 275 C500 355 305 355 230 275"/><text x="320" y="385" font-size="17">O₃ + hν → O₂ + O</text><text x="210" y="430" font-size="16">Trace radicals can catalyse additional destruction cycles.</text>''')
meta(16,'fig16_ozone.svg',None,'original reaction-cycle schematic','Formation and photolysis of stratospheric ozone','تكوّن الأوزون الستراتوسفيري وتحلله الضوئي','Cycle linking oxygen molecule, oxygen atom, and ozone through photolysis and recombination.','دورة تربط جزيء الأكسجين وذرة الأكسجين والأوزون عبر التحلل الضوئي وإعادة الاتحاد.','O₂ photolysis creates reactive O, three-body recombination forms O₃, and ozone absorbs light and photolyzes. Catalytic radical cycles explain why trace species can strongly alter ozone balance.','ينتج تحلل O₂ الضوئي ذرات O نشطة، ويكوّن الاتحاد ثلاثي الأجسام O₃، ثم يمتص الأوزون الضوء ويتحلل. تفسر دورات الجذور الحفازة أثر الأنواع النزرة الكبير في توازن الأوزون.')
# 17 LJ
x=np.linspace(.82,3,350);y=4*(x**-12-x**-6)
plot('fig17_lj','Lennard–Jones 12–6 pair potential','Separation r/σ','Potential U/ε',[(x,y,'12–6 model')],ylim=(-1.25,3));d=csvsave('fig17_lj',['r_over_sigma','U_over_epsilon'],zip(x[::7],y[::7]))
meta(17,'fig17_lj.svg',d,'theoretical pair-potential graph','Repulsion, attraction, and the Lennard–Jones minimum','التنافر والتجاذب وقاع جهد لينارد–جونز','Lennard-Jones potential with steep short-range repulsion, negative minimum, and long-range approach to zero.','جهد لينارد–جونز بتنافر حاد قصير المدى وقيمة صغرى سالبة واقتراب بعيد المدى من الصفر.','The r⁻¹² and r⁻⁶ terms model repulsion and dispersion. Their balance yields the well minimum. The 12–6 form is a useful model, not a universal exact intermolecular potential.','يمثل حدّا r⁻¹² وr⁻⁶ التنافر والتشتت ويعطي توازنهما قاع الجهد. صيغة 12–6 نموذج مفيد وليست جهداً دقيقاً عالمياً.')
# 18 Bragg
svg('fig18_bragg','''<line class="s" x1="80" y1="160" x2="740" y2="160"/><line class="s" x1="80" y1="300" x2="740" y2="300"/><line class="g" x1="40" y1="70" x2="320" y2="160"/><line class="g" x1="320" y1="160" x2="620" y2="65"/><line class="g" x1="40" y1="210" x2="320" y2="300"/><line class="g" x1="320" y1="300" x2="620" y2="205"/><line class="d" x1="320" y1="160" x2="320" y2="300"/><text x="335" y="238" font-size="20">d</text><text x="255" y="145" font-size="18">θ</text><text x="220" y="400" font-size="24">nλ = 2d sinθ</text>''')
meta(18,'fig18_bragg.svg',None,'original diffraction-geometry schematic','Bragg diffraction from parallel lattice planes','حيود براج من مستويات شبكية متوازية','Two crystal planes and two rays showing interplanar spacing d and angle theta for the Bragg condition.','مستويان بلوريان وشعاعان يوضحان المسافة d والزاوية ثيتا لشرط براج.','Constructive interference occurs when the extra path equals an integer wavelength, nλ=2d sinθ. Diffraction peaks encode lattice spacings; they are not literal mirror reflections from planes.','يحدث التداخل البنّاء عندما يساوي فرق المسار عدداً صحيحاً من الأطوال الموجية nλ=2d sinθ. ترمز قمم الحيود إلى المسافات الشبكية ولا تمثل انعكاساً مرآتياً حرفياً.')
# 19 diffusion
x=np.linspace(-4,4,350);series=[];rows=[]
for tau in [.25,1,4]:
 y=np.array([.5*(1-math.erf(a/(2*math.sqrt(tau)))) for a in x]);series.append((x,y,f'Dt={tau:g}'));rows += [[tau,float(a),float(b)] for a,b in zip(x[::7],y[::7])]
plot('fig19_diffusion','Diffusive smoothing of a concentration step','Scaled position','Normalized concentration',series);d=csvsave('fig19_diffusion',['scaled_Dt','scaled_x','normalized_c'],rows)
meta(19,'fig19_diffusion.svg',d,'calculated diffusion-model graph','Fickian diffusion broadens concentration gradients','الانتشار الفيكي يوسّع تدرجات التركيز','Three concentration profiles broaden with increasing scaled diffusion time.','ثلاثة منحنيات تركيز تتسع مع زيادة الزمن الانتشاري المقياس.','Fick’s second law smooths gradients over a characteristic distance proportional to √(Dt). In the ideal model diffusion redistributes conserved material rather than creating it.','يملس قانون فيك الثاني التدرجات على مسافة تتناسب مع √(Dt). في النموذج المثالي يعيد الانتشار توزيع المادة المحفوظة ولا يخلقها.')
# 20 Boltzmann
T=np.linspace(80,1200,320);r=np.exp(-5000/(R*T));pe=r/(1+r);pg=1-pe
plot('fig20_boltzmann','Two-level Boltzmann populations (ΔE = 5 kJ mol⁻¹)','Temperature / K','Population fraction',[(T,pg,'ground'),(T,pe,'excited')]);d=csvsave('fig20_boltzmann',['T_K','ground','excited'],zip(T[::6],pg[::6],pe[::6]))
meta(20,'fig20_boltzmann.svg',d,'calculated statistical graph','Thermal population of a two-level system','السكان الحراري لنظام ثنائي المستويات','Ground and excited population fractions versus temperature for a five kilojoule per mole gap.','كسرا سكان الحالة الأرضية والمثارة مقابل الحرارة لفجوة خمسة كيلوجول لكل مول.','At low T the excited state is strongly suppressed. As RT approaches ΔE, excitation becomes significant; with equal degeneracy the two levels approach equal population only at very high T.','عند الحرارة المنخفضة يكون إشغال الحالة المثارة ضعيفاً. عندما يقترب RT من ΔE تصبح الإثارة مهمة، ومع انحلالين متساويين يقترب السكان من التساوي فقط عند الحرارة العالية جداً.')
(Path('/mnt/data/pchem_build/visuals.json')).write_text(json.dumps(V,ensure_ascii=False,indent=2),encoding='utf-8')
print('figures',len(V))
