(() => {
  const body=document.body, langBtn=document.getElementById('langToggle');
  function setMode(m){body.classList.remove('mode-en','mode-ar');body.classList.add('mode-'+m);document.documentElement.lang=m==='ar'?'ar':'en';document.documentElement.dir=m==='ar'?'rtl':'ltr';localStorage.setItem('qm-lang',m);if(langBtn)langBtn.textContent=m==='ar'?'EN':'ع';}
  setMode(localStorage.getItem('qm-lang')||'en');
  langBtn?.addEventListener('click',()=>setMode(body.classList.contains('mode-ar')?'en':'ar'));
  document.getElementById('printBtn')?.addEventListener('click',()=>window.print());
  const panel=document.getElementById('searchPanel'),input=document.getElementById('searchInput'),results=document.getElementById('searchResults');
  document.getElementById('searchBtn')?.addEventListener('click',()=>{panel.classList.toggle('open');if(panel.classList.contains('open'))input.focus();});
  document.getElementById('searchClose')?.addEventListener('click',()=>panel.classList.remove('open'));
  input?.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();results.innerHTML='';if(q.length<2)return;document.querySelectorAll('.module,.section').forEach(el=>{if(el.innerText.toLowerCase().includes(q)){const a=document.createElement('a');a.className='search-result';a.href='#'+el.id;a.textContent=(el.querySelector('h2')?.innerText||el.id).slice(0,140);a.onclick=()=>panel.classList.remove('open');results.appendChild(a);}})});
  const ids=[...document.querySelectorAll('.module')].map(x=>x.id),seen=new Set(JSON.parse(localStorage.getItem('qm-seen')||'[]'));
  function progress(){const pct=ids.length?Math.round(100*seen.size/ids.length):0;document.getElementById('progressBar')?.style.setProperty('width',pct+'%');const x=document.getElementById('progressText');if(x)x.textContent=pct+'%';}
  const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&e.intersectionRatio>.3){seen.add(e.target.id);localStorage.setItem('qm-seen',JSON.stringify([...seen]));progress();}}),{threshold:[.3]});document.querySelectorAll('.module').forEach(m=>obs.observe(m));progress();
  const bookmarks=new Set(JSON.parse(localStorage.getItem('qm-bookmarks')||'[]'));document.querySelectorAll('.bookmark').forEach(b=>{const id=b.dataset.target;const paint=()=>b.textContent=bookmarks.has(id)?'★ Saved':'☆ Bookmark';paint();b.onclick=()=>{bookmarks.has(id)?bookmarks.delete(id):bookmarks.add(id);localStorage.setItem('qm-bookmarks',JSON.stringify([...bookmarks]));paint();};});
  // Interactive infinite square well
  const bc=document.getElementById('boxCanvas'); if(bc){const n=document.getElementById('boxN'),L=document.getElementById('boxL'),lab=document.getElementById('boxLabel'),ctx=bc.getContext('2d');function draw(){const dpr=devicePixelRatio||1,w=bc.clientWidth,h=350;bc.width=w*dpr;bc.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const N=+n.value,ell=+L.value;const ml=50,mr=20,mt=20,mb=45;const X=x=>ml+x/ell*(w-ml-mr),Y=y=>mt+(1-y)/2*(h-mt-mb);ctx.strokeStyle='#77808e';ctx.beginPath();ctx.moveTo(ml,mt);ctx.lineTo(ml,h-mb);ctx.lineTo(w-mr,h-mb);ctx.stroke();ctx.strokeStyle='#3d4a7e';ctx.lineWidth=2.2;ctx.beginPath();for(let i=0;i<=500;i++){const x=ell*i/500,psi=Math.sin(N*Math.PI*x/ell);const px=X(x),py=Y(psi);i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.stroke();ctx.fillStyle='#222';ctx.font='13px Arial';ctx.fillText('0',ml-4,h-mb+20);ctx.fillText(ell.toFixed(1)+' nm',w-70,h-mb+20);ctx.fillText('ψ',15,25);const eEv=0.3760302*N*N/(ell*ell);lab.textContent=`n=${N}; L=${ell.toFixed(1)} nm; E_n≈${eEv.toFixed(3)} eV for an electron.`;}n.oninput=draw;L.oninput=draw;addEventListener('resize',draw);draw();}
  // Tunneling approximation explorer
  const tc=document.getElementById('tunnelCanvas'); if(tc){const wIn=document.getElementById('barrierW'),vIn=document.getElementById('barrierV'),tl=document.getElementById('tunnelLabel'),ctx=tc.getContext('2d');function draw(){const dpr=devicePixelRatio||1,W=tc.clientWidth,H=350;tc.width=W*dpr;tc.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);const a=+wIn.value,V0=+vIn.value,E=1.0;const hbar=1.054571817e-34,m=9.1093837139e-31,e=1.602176634e-19,kappa=Math.sqrt(2*m*(V0-E)*e)/hbar,T=Math.exp(-2*kappa*a*1e-9);const x1=W*.35,x2=W*.65,y0=H*.78,yV=H*.25,yE=H*.48;ctx.strokeStyle='#202a43';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(30,y0);ctx.lineTo(x1,y0);ctx.lineTo(x1,yV);ctx.lineTo(x2,yV);ctx.lineTo(x2,y0);ctx.lineTo(W-20,y0);ctx.stroke();ctx.setLineDash([7,5]);ctx.strokeStyle='#9a5d18';ctx.beginPath();ctx.moveTo(30,yE);ctx.lineTo(W-20,yE);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#222';ctx.font='13px Arial';ctx.fillText(`E = ${E.toFixed(1)} eV`,35,yE-8);ctx.fillText(`V₀ = ${V0.toFixed(1)} eV`,x1+8,yV-8);ctx.fillText(`a = ${a.toFixed(2)} nm`,x1+18,y0+24);tl.textContent=`Approximate electron transmission T ≈ exp(-2κa) = ${T.toExponential(3)}. Increase mass, height, or width and tunnelling falls exponentially.`;}wIn.oninput=draw;vIn.oninput=draw;addEventListener('resize',draw);draw();}
})();
