(() => {
  const body=document.body;
  const langBtn=document.getElementById('langToggle');
  function setMode(m){body.classList.remove('mode-en','mode-ar');body.classList.add('mode-'+m);document.documentElement.lang=m==='ar'?'ar':'en';document.documentElement.dir=m==='ar'?'rtl':'ltr';localStorage.setItem('cc-lang',m);if(langBtn)langBtn.textContent=m==='ar'?'EN':'ع';}
  setMode(localStorage.getItem('cc-lang')||'en');
  if(langBtn) langBtn.addEventListener('click',()=>setMode(body.classList.contains('mode-ar')?'en':'ar'));
  document.getElementById('printBtn')?.addEventListener('click',()=>window.print());
  const searchPanel=document.getElementById('searchPanel'), searchInput=document.getElementById('searchInput'), results=document.getElementById('searchResults');
  document.getElementById('searchBtn')?.addEventListener('click',()=>{searchPanel.classList.toggle('open'); if(searchPanel.classList.contains('open')) searchInput.focus();});
  document.getElementById('searchClose')?.addEventListener('click',()=>searchPanel.classList.remove('open'));
  searchInput?.addEventListener('input',()=>{const q=searchInput.value.trim().toLowerCase();results.innerHTML='';if(q.length<2)return;document.querySelectorAll('.module,.section').forEach(el=>{const txt=el.innerText.toLowerCase();if(txt.includes(q)){const a=document.createElement('a');a.className='search-result';a.href='#'+el.id;a.textContent=(el.querySelector('h2')?.innerText||el.id).slice(0,120);a.onclick=()=>searchPanel.classList.remove('open');results.appendChild(a);}})});
  const moduleIds=[...document.querySelectorAll('.module')].map(x=>x.id);
  const seen=new Set(JSON.parse(localStorage.getItem('cc-seen')||'[]'));
  function updateProgress(){const pct=moduleIds.length?Math.round(100*seen.size/moduleIds.length):0;document.getElementById('progressBar')?.style.setProperty('width',pct+'%');const x=document.getElementById('progressText');if(x)x.textContent=pct+'%';}
  const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting && e.intersectionRatio>.35){seen.add(e.target.id);localStorage.setItem('cc-seen',JSON.stringify([...seen]));updateProgress();}}),{threshold:[.35]});document.querySelectorAll('.module').forEach(m=>observer.observe(m));updateProgress();
  const bookmarks=new Set(JSON.parse(localStorage.getItem('cc-bookmarks')||'[]'));document.querySelectorAll('.bookmark').forEach(b=>{const id=b.dataset.target;function paint(){b.textContent=bookmarks.has(id)?'★ Saved':'☆ Bookmark'}paint();b.addEventListener('click',()=>{bookmarks.has(id)?bookmarks.delete(id):bookmarks.add(id);localStorage.setItem('cc-bookmarks',JSON.stringify([...bookmarks]));paint();});});
  // Lennard-Jones theoretical parameter explorer
  const c=document.getElementById('ljCanvas'); if(c){const ctx=c.getContext('2d'); const eps=document.getElementById('eps'),sig=document.getElementById('sig'); const label=document.getElementById('ljLabel'); function draw(){const dpr=window.devicePixelRatio||1,w=c.clientWidth,h=340;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const E=+eps.value,S=+sig.value;const xmin=.8*S,xmax=3*S,ymin=-1.2*E,ymax=3.5*E;const X=x=>55+(x-xmin)/(xmax-xmin)*(w-75),Y=y=>15+(ymax-y)/(ymax-ymin)*(h-55);ctx.strokeStyle='#7a8792';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(55,15);ctx.lineTo(55,h-40);ctx.lineTo(w-20,h-40);ctx.stroke();ctx.strokeStyle='#17395c';ctx.lineWidth=2;ctx.beginPath();let first=true;for(let i=0;i<=500;i++){const r=xmin+(xmax-xmin)*i/500;let u=4*E*(Math.pow(S/r,12)-Math.pow(S/r,6));u=Math.min(ymax,u);const x=X(r),y=Y(u);if(first){ctx.moveTo(x,y);first=false}else ctx.lineTo(x,y)}ctx.stroke();const rmin=Math.pow(2,1/6)*S;ctx.fillStyle='#b58b31';ctx.beginPath();ctx.arc(X(rmin),Y(-E),5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#263644';ctx.font='13px Arial';ctx.fillText('r',w-30,h-22);ctx.fillText('U(r)',8,25);ctx.fillText('minimum: r = 2^(1/6)σ',Math.max(65,X(rmin)-75),Y(-E)+28);label.textContent=`ε=${E.toFixed(2)} kJ mol⁻¹; σ=${S.toFixed(2)} Å; r_min=${rmin.toFixed(2)} Å; U_min=${(-E).toFixed(2)} kJ mol⁻¹`;}
    eps.addEventListener('input',draw);sig.addEventListener('input',draw);window.addEventListener('resize',draw);draw();}
})();
